# -*- coding: utf-8 -*-
"""prime_or_not.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gcf7VG56vlLS73r9nQAP5uUCDJJw52_H

**1) Write a Program which has function to find out a number is prime or not.**
"""

from math import sqrt

n = 11 # Enter Number you want to check..

flag = 0

if(n > 1):
	for k in range(2, int(sqrt(n)) + 1):
		if (n % k == 0):
			flag = 1
		break
	if (flag == 0):
		print(n," is a Prime Number..!")
	else:
		print(n," is Not a Prime Number..!")
else:
	print(n," is Not a Prime Number..!")