# -*- coding: utf-8 -*-
"""User_E_Even_odd.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SryCjpUlQuhNfeg9kHl9k1OjG521sAM1

**1) Write a Python program to find whether a given number (accept from the user) is even or odd**
"""

num = int(input("Enter a number: "))
if (num % 2) == 0:
   print("{0} is Even".format(num))
else:
   print("{0} is Odd".format(num))